config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  get '/sign_in', as: 'signin', to: 'sessions#signin'
  get '/sign_out', as: 'signout', to: 'sessions#signout'
  get '/sign_up', as: 'signup', to: 'sessions#signup'

  get 'auth/sign_in', to: 'auth#signin'
  get 'auth/sign_out', to: 'auth#signout'

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cognito_session.rb
class CognitoSession < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cognito_sessions
end

app/controllers/application_controller.rb
require 'cognito_jwt_keys'
require 'cognito_client'

class ApplicationController < ActionController::Base
  before_action :check_signed_in

  def check_signed_in
    @is_signed_in = false
    @current_user = nil
    @cognito_session = nil

    cognito_session = nil
    if session[:cognito_session_id]
      begin
        cognito_session = CognitoSession.find(session[:cognito_session_id])
      rescue ActiveRecord::RecordNotFound
      end
    end

    unless cognito_session
      return
    end

    now = Time.now.tv_sec

    if cognito_session.expire_time > now
      # Still valid, use
      #

      Rails.logger.info("Found a non-expired cognito session: #{cognito_session.id}")
      @is_signed_in = true
      @current_user = cognito_session.user
      @cognito_session = cognito_session
      return
    end

    Rails.logger.info("Refreshing cognito session: #{cognito_session.id}")

    # Need to refresh token
    if refresh_cognito_session(cognito_session)
      @is_signed_in = true
      @current_user = cognito_session.user
      @cognito_session = cognito_session
      return
    end
  end

  def refresh_cognito_session(cognito_session)
    client = new_cognito_client()

    resp = client.refresh_id_token(cognito_session.refresh_token)

    return false unless resp

    cognito_session.expire_time = resp.id_token[:exp]
    cognito_session.issued_time = resp.id_token[:auth_time]
    cognito_session.audience = resp.id_token[:aud]

    cognito_session.save!
  end

  def new_cognito_client
    CognitoClient.new(:redirect_uri => auth_sign_in_url)
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def signin
    unless params[:code]
      render :nothing => true, :status => :bad_request
      return
    end

    resp = lookup_auth_code(params[:code])
    unless resp
      redirect_to '/'
      return
    end

    ActiveRecord::Base.transaction do
      user = User.find_or_initialize_by(subscriber: resp.id_token[:sub])
      if user.nil?
        user = User.create(subscriber: resp.id_token[:sub],
                           email: resp.id_token[:email])
      end

      cognito_session = CognitoSession.create(user: user,
                                              expire_time: resp.id_token[:exp],
                                              issued_time: resp.id_token[:auth_time],
                                              audience: resp.id_token[:aud],
                                              refresh_token: resp.refresh_token)
      session[:cognito_session_id] = cognito_session.id
    end

    # Alternatively, you could redirect to a saved URL
    redirect_to '/'
  end

  def signout
    if cognito_session_id = session[:cognito_session_id]
      cognito_session = CognitoSession.find(cognito_session_id) rescue nil
      cognito_session.destroy if cognito_session
      session.delete(:cognito_session_id)
    end

    redirect_to '/'
  end

  def lookup_auth_code(code)
    client = new_cognito_client()
    client.get_pool_tokens(code)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signin
    redirect_to cognito_signin_url
  end

  def signout
    redirect_to cognito_signout_url
  end

  def signup
    redirect_to cognito_signup_url
  end

private

  def cognito_signin_url
    CognitoUrls.login_uri(ENV['AWS_COGNITO_APP_CLIENT_ID'],
                          signin_redirect_uri)
  end

  def cognito_signup_url
    CognitoUrls.signup_uri(ENV['AWS_COGNITO_APP_CLIENT_ID'],
                           signin_redirect_uri)
  end

  def cognito_signout_url
    CognitoUrls.logout_uri(ENV['AWS_COGNITO_APP_CLIENT_ID'],
                           signout_redirect_uri)
  end

  def signin_redirect_uri
    auth_sign_in_url
  end

  def signout_redirect_uri
    auth_sign_out_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/_user.html.erb
<h2>Signed in</h2>
<ul>
  <li>Email: <mark><%= @current_user.email %></mark></li>
  <li>ID Token Subject: <mark><%= @current_user.subscriber %></mark></li>
  <li>ID Token Issued: <mark><%= Time.at(@cognito_session.issued_time).utc %></mark></li>
  <li>ID Token Expiration: <mark><%= Time.at(@cognito_session.expire_time).utc %></mark></li>
</ul>

app/views/home/index.html.erb
<% if (!@is_signed_in) %>
<h2>Please sign in.</h2>
<% else %>
<%= render 'user' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCognitoUserPoolExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
      <header>
        <a href="#" class="logo">Rails Cognito Example</a>
      </header>
        <% if (!@is_signed_in) %>
          <a href="<%= signin_path %>" class="button">Sign In</a>
          <a href="<%= signup_path %>" class="button">Sign Up</a>
        <% else %>
          <a href="<%= signout_path %>" class="button">Sign Out</a>
        <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>